apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    # labels are used for selector
    project: roboshop
    tier: db
    component: mysql
  ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # container port