apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: redis
spec: 
  replicas: {{ .Values.deployment.replica }}
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: redis
  template:
    metadata:
      name: redis
      labels:
        project: roboshop
        tier: db
        component: redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}"